# typed: false
# frozen_string_literal: true

# Homebrew formula for adacli — generated by scripts/render-formula.mjs. Do not edit by hand;
# the release workflow regenerates it on every release.
class Adacli < Formula
  desc "Agent-native CLI for managing and improving Ada AI Agents"
  homepage "https://github.com/AdaSupport/homebrew-tap"
  version "0.3.1"
  # Proprietary — AdaCLI License Notice (© Ada Support Inc.), not an SPDX/open-source license.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.1/adacli-darwin-arm64.tar.gz"
      sha256 "06ef1ba4b76da6203db6facf31e224416d8a4d452f113d81befccc104981d491"
    end
    on_intel do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.1/adacli-darwin-x64.tar.gz"
      sha256 "b2bcd79d81d9441430fc0076a9118eeae4ef24a5147f4d8a42f649c79fe12ffb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.1/adacli-linux-arm64.tar.gz"
      sha256 "73ba0f6213a6d0b50cd8e539564ab496e948eaa9b9bcae5a00623b3abec4492b"
    end
    on_intel do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.1/adacli-linux-x64.tar.gz"
      sha256 "2de49edcc5d9d5e2f187188d1075f111783b0e0a60f20f210022abdb8d8dd896"
    end
  end

  def install
    bin.install "adacli"
    prefix.install "LICENSE" # AdaCLI License Notice ships alongside the binary
  end

  def caveats
    <<~EOS
      The macOS binary is ad-hoc signed but not yet notarized. Installed via Homebrew it runs with no
      Gatekeeper prompt. If you copy it elsewhere and macOS blocks it, clear the quarantine flag once:
        xattr -d com.apple.quarantine "$(which adacli)"
    EOS
  end

  test do
    # Exercise more than --version: the command tree must initialize and an embedded doc must read,
    # all offline (no network/auth) so the runtime is verified end-to-end, not just the version string.
    assert_match version.to_s, shell_output("#{bin}/adacli --version")
    assert_match "Usage:", shell_output("#{bin}/adacli --help")
    assert_match "adacli", shell_output("#{bin}/adacli docs guide")
  end
end
