# typed: false
# frozen_string_literal: true

# Homebrew formula for adacli — generated by scripts/render-formula.mjs. Do not edit by hand;
# the release workflow regenerates it on every release.
class Adacli < Formula
  desc "Agent-native CLI for managing and improving Ada AI Agents"
  homepage "https://github.com/AdaSupport/homebrew-tap"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.0/adacli-darwin-arm64.tar.gz"
      sha256 "aed560ba20e65c569796681f4bf9337c84f900099984b174ae5959501034ee28"
    end
    on_intel do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.0/adacli-darwin-x64.tar.gz"
      sha256 "b6319101a32d4970150a1f10fd955ed2dd45cea433e32ecece7c00e8d8c2095a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.0/adacli-linux-arm64.tar.gz"
      sha256 "725d27dfc5eff1366456ddb9a8649ea29e0c0bbf905484cdd6b508bdad58b764"
    end
    on_intel do
      url "https://github.com/AdaSupport/homebrew-tap/releases/download/adacli-v0.3.0/adacli-linux-x64.tar.gz"
      sha256 "0500d1f61c2891bcb426ee7db7fdaa66881fe7212e4b64368cfb47528f5719ef"
    end
  end

  def install
    bin.install "adacli"
  end

  def caveats
    <<~EOS
      The macOS binary is ad-hoc signed but not yet notarized. Installed via Homebrew it runs with no
      Gatekeeper prompt. If you copy it elsewhere and macOS blocks it, clear the quarantine flag once:
        xattr -d com.apple.quarantine "$(which adacli)"
    EOS
  end

  test do
    # Exercise more than --version: the command tree must initialize and an embedded doc must read,
    # all offline (no network/auth) so the runtime is verified end-to-end, not just the version string.
    assert_match version.to_s, shell_output("#{bin}/adacli --version")
    assert_match "Usage:", shell_output("#{bin}/adacli --help")
    assert_match "adacli", shell_output("#{bin}/adacli docs guide")
  end
end
